name: charset
description: Charset encoding and decoding Library, include iso-(2-15), windows series, gbk, euc-jp, euc-kr, shift-jis. And supportted charset detect, canEncode, canDecode.
version: 2.0.1
homepage:
repository: https://github.com/shirne/charset-dart

environment:
  sdk: ">=2.12.0 <4.0.0"

dependencies:

dev_dependencies:
  test:
  lints: ^2.0.1

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
