name: charset
description: Multiple charset Encoding and Decoding Library.
version: 0.2.3
homepage:
repository: https://github.com/shirne/charset-dart
publish_to: https://pub.dartlang.org

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test:

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
