name: charset
description: Charset encoding and decoding Library, include iso-(2-15), windows series, gbk, euc-jp, euc-kr, shift-jis. And supportted charset detect, canEncode, canDecode.
version: 1.1.0
homepage:
repository: https://github.com/shirne/charset-dart

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:

dev_dependencies:
  test:
  flutter_lints: ^1.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
